export const appText = {
    common: {
        locale: 'pl-PL',
        actions: {
            add: 'Dodaj',
            cancel: 'Anuluj',
            delete: 'Usuń',
            save: 'Zapisz',
            retry: 'Ponów',
        },
        media: {
            photo: 'Zdjęcie',
            photoLower: 'zdjęcie',
            video: 'Film',
            videoLower: 'film',
            mediaLower: 'medium',
            mediaPlural: 'mediów',
            openOrDownloadVideo: 'Otwórz/pobierz film',
            photoPreviewAlt: 'Podgląd zdjęcia',
            weddingPhotoAlt: 'Zdjęcie z wesela',
            noCover: 'Album bez okładki',
        },
        status: {
            ready: 'Gotowe',
            processing: 'Przetwarzanie',
            failed: 'Błąd',
            visible: 'Widoczny',
            hidden: 'Ukryty',
            visibleForGuests: 'Widoczne dla gości',
        },
        pagination: {
            next: 'Następna',
            previous: 'Poprzednia',
        },
        toggles: {
            yes: 'Tak',
            no: 'Nie',
        },
    },
    errors: {
        auth: {
            sessionExpired: 'Sesja wygasła. Zaloguj się ponownie.',
            accessDenied: 'Brak dostępu do tej sekcji.',
            incompleteGuestLogin: 'Logowanie kodem zwróciło niepełną odpowiedź.',
            incompleteAdminLogin: 'Logowanie admina zwróciło niepełną odpowiedź.',
        },
        byCode: {
            MENU_NOT_FOUND: 'Menu weselne nie zostało jeszcze opublikowane.',
            EVENTS_NOT_FOUND: 'Wydarzenia nie zostały jeszcze opublikowane.',
            SCHEDULE_NOT_FOUND: 'Harmonogram dnia nie został jeszcze opublikowany.',
            UNHANDLED_ERROR: 'Wystąpił problem po stronie serwera. Spróbuj ponownie później.',
        },
        byStatus: {
            400: 'Nie udało się przetworzyć żądania. Spróbuj ponownie.',
            401: 'Brak dostępu do tych danych.',
            403: 'Brak dostępu do tych danych.',
            404: 'Szukane dane nie są obecnie dostępne.',
            500: 'Wystąpił problem po stronie serwera. Spróbuj ponownie później.',
            502: 'Usługa jest chwilowo niedostępna. Spróbuj ponownie później.',
            503: 'Usługa jest chwilowo niedostępna. Spróbuj ponownie później.',
        },
        debug: {
            title: 'Title',
            code: 'Code',
            traceId: 'Trace ID',
            stackTrace: 'Stack trace:',
        },
        fallback: {
            menu: 'Nie udało się pobrać menu.',
            events: 'Nie udało się pobrać harmonogramu dnia.',
            photos: 'Nie udało się pobrać zdjęć.',
            galleryAlbums: 'Nie udało się pobrać albumów.',
            galleryAlbum: 'Nie udało się pobrać albumu.',
            albumMedia: 'Nie udało się pobrać mediów albumu.',
            adminOverview: 'Nie udało się pobrać danych panelu.',
            adminMedia: 'Nie udało się pobrać mediów.',
            adminGuestbook: 'Nie udało się pobrać życzeń.',
            adminGuests: 'Nie udało się pobrać listy gości.',
            adminSlideshow: 'Nie udało się pobrać ustawień pokazu slajdów.',
        },
    },
    navigation: {
        items: {
            menu: 'Menu wesela',
            attractions: 'Atrakcje',
            events: 'Wydarzenia',
            upload: 'Dodaj zdjęcie/film',
            gallery: 'Galeria',
            guestbook: 'Księga gości',
        },
        adminDisplayNameFallback: 'Państwo Młodzi',
        adminPanel: 'Panel Młodej Pary',
        mobileMenuToggle: 'Toggle menu',
        logout: 'Wyloguj się',
    },
    footer: {
        text: 'Stworzone dla naszego wyjątkowego dnia',
    },
    menu: {
        defaultBlockTitle: 'Główne menu weselne',
        sectionTypes: {
            przystawka: 'Przystawka',
            zupa: 'Zupa',
            danie_glowne: 'Danie główne',
            deser: 'Deser',
            zimna_plyta: 'Zimna płyta',
            napoje: 'Napoje',
            slodki_stol: 'Słodki stół',
            inne: 'Inne',
        },
    },
    public: {
        home: {
            couple: {
                first: 'Alicja',
                second: 'Piotr',
                date: '31 lipca 2026',
                location: 'Willa Poprad',
            },
            quickLinks: {
                menu: {
                    title: 'Menu wesela',
                    description: 'Zobacz, co serwujemy',
                },
                attractions: {
                    title: 'Atrakcje',
                    description: 'Co przygotowaliśmy',
                },
                events: {
                    title: 'Wydarzenia',
                    description: 'Harmonogram dnia',
                },
                gallery: {
                    title: 'Galeria',
                    description: 'Zobacz albumy',
                },
                upload: {
                    title: 'Dodaj zdjęcie/film',
                    description: 'Podziel się wspomnieniami',
                },
                guestbook: {
                    title: 'Księga gości',
                    description: 'Zostaw życzenia',
                },
            },
            welcome: {
                title: 'Witajcie w naszym dniu',
                firstParagraph: 'Z radością zapraszamy Was do wspólnego świętowania! To wyjątkowy dzień, który chcemy przeżyć razem wami - najbliższymi nam osobami.',
                secondParagraph: 'Na tej stronie znajdziecie wszystkie informacje dotyczące naszego wesela, a także będziecie mogli podzielić się z nami swoimi zdjęciami, wspomnieniami czy życzeniami.',
            },
            guestInfoTitle: 'Informacje dla gości',
            cta: {
                title: 'Nie możemy się doczekać!',
                description: 'Dziękujemy, że będziecie z nami w tym wyjątkowym dniu',
                upload: 'Dodaj zdjęcie/film',
                guestbook: 'Zostaw życzenia',
            },
        },
        access: {
            adminRequired: 'Ta sekcja wymaga dostępu administratora. Zaloguj się poniżej jako admin.',
            guestLoggedInForAdmin: 'Jesteś zalogowany jako gość. Aby wejść do panelu, użyj danych administratora.',
            qrChecking: 'Trwa sprawdzanie kodu dostępu z kodu QR.',
            guestDescription: 'Aby uzyskać dostęp do aplikacji, wpisz kod dostępu lub zeskanuj kod QR dostępny na sali.',
            adminDescription: 'Zaloguj się jako admin.',
            adminTitle: 'Młoda Para',
            guestTitle: 'Wymagany dostęp',
            fields: {
                email: 'Email',
                password: 'Hasło',
                accessCode: 'Kod dostępu',
            },
            placeholders: {
                adminEmail: 'admin@marryly.pl',
                accessCode: 'Wpisz kod dostępu',
            },
            actions: {
                goToAdmin: 'Przejdź do panelu admina',
                backToGuestLogin: 'Wróć do logowania jako gość',
                enterApp: 'Wejdź do aplikacji',
                loginAsAdmin: 'Zaloguj się jako admin',
                or: 'lub',
            },
            errors: {
                useCode: 'Nie udało się użyć kodu dostępu.',
                guestLogin: 'Nie udało się zalogować kodem dostępu.',
                adminLogin: 'Nie udało się zalogować do panelu.',
            },
        },
        menu: {
            title: 'Menu wesela',
            empty: 'Menu weselne wkrótce zostanie opublikowane',
        },
        events: {
            title: 'Wydarzenia',
            empty: 'Wkrótce pojawi się tutaj harmonogram dnia',
        },
        attractions: {
            title: 'Atrakcje',
            description: 'Wkrótce pojawi się tutaj lista atrakcji przygotowanych na wesele',
        },
        gallery: {
            title: 'Galeria',
            description: 'Wybierz album, który chcesz obejrzeć.',
            empty: 'Galeria będzie widoczna, gdy pojawi się pierwszy album.',
            coverAltPrefix: 'Okładka albumu',
            defaultAlbumDescription: 'Otwórz album, aby zobaczyć zawartość.',
            defaultGuestAlbumTitle: 'Od gości',
            defaultGuestAlbumDescription: 'Zdjęcia dodane przez gości.',
            albumFallbackTitle: 'Galeria',
            albumFallbackDescription: 'Album z naszymi wspomnieniami.',
            albumEmpty: 'Ten album jest jeszcze pusty.',
            loadMore: 'Pokaż więcej mediów',
        },
        guestUpload: {
            title: 'Dodaj zdjęcia i filmy',
            description: 'Zrób lub wybierz zdjęcia albo filmy, a wysyłanie rozpocznie się automatycznie.',
            addButtonLabel: 'Dodaj zdjęcia lub filmy',
            addButtonDescription: 'Otworzy aparat, kamerę lub galerię w telefonie.',
            successTitle: 'Pliki zapisane',
        },
        guestbook: {
            title: 'Księga gości',
            description: 'Zostaw nam swoje życzenia i wspomnienia z tego dnia',
            success: 'Dziękujemy! Twoje życzenia zostały zapisane.',
            fields: {
                name: 'Twoje imię',
                message: 'Twoja wiadomość',
            },
            placeholders: {
                name: 'Jakub Puszysty',
                message: 'Podziel się z nami czymkolwiek chcesz...',
            },
            attachment: {
                idle: 'Załącznik opcjonalny',
                preparingPrefix: 'Przygotowujemy',
                uploadingPrefix: 'Przesyłamy',
                completingPrefix: 'Zapisujemy',
                photoSuccess: 'Zdjęcie załączone',
                videoSuccess: 'Film załączony',
                errorPrefix: 'Nie udało się załączyć',
                title: 'Zdjęcie lub film',
                description: 'Możesz dołączyć zdjęcie albo krótki film z telefonu.',
                add: 'Dodaj załącznik',
                change: 'Zmień załącznik',
                overlayDescription: 'Nie odświeżaj strony ani nie zamykaj karty. Po zakończeniu załącznik będzie gotowy do wysłania z życzeniami.',
                unsupportedFormat: 'Wybierz zdjęcie albo film w obsługiwanym formacie.',
                tooLarge: 'Plik jest większy niż',
                tooLargeAfterPreparing: 'Plik po przygotowaniu jest większy niż',
                uploadFailed: 'Nie udało się załączyć pliku. Spróbuj ponownie.',
            },
            submit: 'Wyślij życzenia',
            submitFailed: 'Nie udało się wysłać życzeń. Spróbuj ponownie.',
        },
        slideshow: {
            refreshFailed: 'Nie udało się odświeżyć kolejki zdjęć.',
            startFailed: 'Nie udało się uruchomić pokazu slajdów.',
            loadingTitle: 'Uruchamianie pokazu',
            loadingDescription: 'Przygotowuję zdjęcia i konfigurację pełnoekranowego odtwarzania.',
            unavailableTitle: 'Pokaz chwilowo niedostępny',
            waitingTitle: 'Czekam na zdjęcia',
            waitingDescription: 'Gdy w wybranym albumie pojawią się gotowe zdjęcia, pokaz wystartuje automatycznie.',
        },
    },
    components: {
        adminBackLink: {
            label: 'Powrót do panelu',
            shortLabel: 'Panel',
        },
        apiErrorAlert: {
            refresh: 'Spróbuj odświeżyć stronę',
        },
        galleryGrid: {
            nextAriaLabel: 'Następne medium',
        },
        mediaUpload: {
            defaults: {
                addButtonLabel: 'Dodaj zdjęcia',
                addButtonDescription: 'Otworzy aparat lub galerię w telefonie.',
                successTitle: 'Zdjęcia zapisane',
            },
            nouns: {
                fileSingular: 'plik',
                filePaucal: 'pliki',
                filePlural: 'plików',
                photoSingular: 'zdjęcie',
                photoPaucal: 'zdjęcia',
                photoPlural: 'zdjęć',
                photoAccusativeSingular: 'zdjęcia',
                photoGenitivePlural: 'zdjęć',
                videoGenitivePlural: 'filmów',
                photoAndVideoGenitivePlural: 'zdjęć i filmów',
            },
            status: {
                queued: 'Gotowe do wysłania',
                preparing: 'Przygotowywanie uploadu',
                uploading: 'Wysyłanie',
                success: 'Wysłane',
                error: 'Błąd',
            },
            overlay: {
                preparing: 'Przygotowujemy pliki do wysłania',
                uploading: 'Przesyłamy media',
                completing: 'Kończymy zapis',
                description: 'Nie odświeżaj strony ani nie zamykaj karty. Po zakończeniu dostaniesz potwierdzenie.',
                completedSummarySuffix: 'zakończone',
            },
            success: {
                uploadedPrefix: 'Pomyślnie wysłano',
                onePhoto: 'Zdjęcie zostało wysłane. Możesz dodać kolejne.',
                oneFile: 'Plik został wysłany. Możesz dodać kolejne zdjęcia lub filmy.',
                more: 'Możesz dodać kolejne.',
                checkRemaining: 'Sprawdź pozostałe.',
            },
            errors: {
                uploadOne: 'Nie udało się wysłać',
                tryAgain: 'Spróbuj ponownie.',
                maxBatchPrefix: 'Możesz dodać maksymalnie',
                maxBatchSuffix: 'jednocześnie.',
                unsupportedFormat: 'nieobsługiwany format pliku.',
                tooLarge: 'plik jest większy niż',
                duplicate: 'ten plik jest już na liście.',
                partialFailureTitle: 'Nie udało się wysłać części plików',
                partialFailureDescription: 'Możesz ponowić tylko te pozycje, które mają błąd.',
                retryFile: 'Spróbuj wysłać ponownie ten plik.',
            },
        },
    },
    admin: {
        common: {
            dashboardTitle: 'Panel Młodej Pary',
            backToAlbums: 'Powrót do albumów',
            albumsShortLabel: 'Albumy',
            pageSummary: 'Strona',
            deleteMediaConfirm: 'Czy na pewno chcesz usunąć to medium? Ta operacja usunie pliki i wpis w bazie.',
            addedAt: 'Dodano',
            size: 'Rozmiar',
            kind: 'Rodzaj',
            type: 'Typ',
            dimensions: 'Wymiary',
            photoThumbnailAlt: 'Miniatura zdjęcia gościa',
            albumPhotoThumbnailAlt: 'Miniatura zdjęcia z albumu',
            addedByAdmin: 'Dodane przez admina',
            addedByGuest: 'Dodane przez gościa',
        },
        dashboard: {
            helpText: 'Zarządzanie treścią, gośćmi i ustawieniami wesela.',
            guestList: 'Lista gości',
            confirmed: 'Potwierdziło',
            metrics: {
                totalWithCouple: 'Razem z Parą Młodą',
                adults: 'Dorośli',
                vendors: 'Usługodawcy',
                children3To10: 'Dzieci 3-10',
                childrenUnder3: 'Dzieci do 3 lat',
                accommodation: 'Noclegi',
                transport: 'Transport',
            },
            cards: {
                gallery: 'Galeria',
                slideshow: 'Pokaz slajdów',
                wishes: 'Wpisy',
                menu: 'Menu',
                attractions: 'Atrakcje',
                settings: 'Ustawienia',
                live: 'LIVE',
            },
        },
        media: {
            title: 'Media Gości',
            helpText: 'Wszystkie zdjęcia i filmy zapisane dla wydarzenia, także te w trakcie przetwarzania lub z błędem.',
            empty: 'Brak mediów do wyświetlenia.',
            totalSuffix: 'mediów łącznie',
            deleteFailed: 'Nie udało się usunąć medium.',
        },
        albums: {
            title: 'Galeria',
            helpText: 'Zarządzaj albumami widocznymi dla gości i dodawaj nowe kolekcje mediów.',
            newAlbum: 'Nowy album',
            fields: {
                title: 'Tytuł',
                albumTitle: 'Tytuł albumu',
                description: 'Opis',
            },
            placeholders: {
                title: 'Np. Z dzieciństwa',
                description: 'Krótki opis albumu dla gości',
            },
            visiblePublicly: 'Widoczny publicznie',
            create: 'Utwórz album',
            empty: 'Brak albumów do wyświetlenia.',
            system: 'Systemowy',
            custom: 'Niestandardowy',
            slug: 'Slug',
            noDescription: 'Brak opisu albumu.',
            moveUp: 'Wyżej',
            moveDown: 'Niżej',
            edit: 'Edytuj',
            delete: 'Usuń',
            manageMedia: 'Zarządzaj mediami',
            deleteAlbum: 'Usuń album',
            deleteConfirm: 'Czy na pewno chcesz usunąć ten album? Usuń najpierw wszystkie media z albumu.',
            errors: {
                create: 'Nie udało się utworzyć albumu.',
                save: 'Nie udało się zapisać albumu.',
                delete: 'Nie udało się usunąć albumu.',
                reorder: 'Nie udało się zmienić kolejności albumów.',
            },
        },
        album: {
            fallbackTitle: 'Album',
            helpText: 'Zarządzaj mediami przypisanymi do tego albumu.',
            notFound: 'Nie znaleziono wybranego albumu.',
            upload: {
                addButtonLabel: 'Dodaj zdjęcia do albumu',
                addButtonDescription: 'Wybierz zdjęcia, a po przetworzeniu trafią bezpośrednio do tego albumu.',
                successTitle: 'Zdjęcia dodane do albumu',
            },
            empty: 'Ten album nie ma jeszcze żadnych mediów.',
            totalSuffix: 'mediów w albumie',
        },
        guestbook: {
            title: 'Życzenia Gości',
            helpText: 'Wszystkie wiadomości dodane przez gości.',
            empty: 'Brak życzeń od gości.',
            totalSuffix: 'wpisów łącznie',
            photoAlt: 'Załączone zdjęcie',
        },
        slideshow: {
            title: 'Pokaz slajdów',
            helpText: 'Pełnoekranowy pokaz slajdów z wybranych albumów. Możesz ustawić czas wyświetlania zdjęcia i częstotliwość sprawdzania nowych zdjęć w albumach.',
            validationError: 'Wybierz przynajmniej jeden album i uzupełnij poprawnie czasy pokazu.',
            saveFailed: 'Nie udało się zapisać ustawień pokazu slajdów.',
            note: 'Pokaz przestawia zdjęcia dopiero po wczytaniu następnego kadru, więc ekran nie gaśnie między slajdami.',
            fields: {
                albums: 'Albumy źródłowe',
                slideDuration: 'Czas jednego zdjęcia (sekundy)',
                refreshInterval: 'Sprawdzanie nowych zdjęć (sekundy)',
            },
            playbackTitle: 'Konfiguracja odtwarzania',
            lastSaved: 'Ostatni zapis',
            notSavedYet: 'Jeszcze nie zapisano',
            actions: {
                save: 'Zapisz ustawienia',
                fullscreen: 'Uruchom pełny ekran',
            },
            saveBeforeStart: 'Zapisz zmiany, zanim uruchomisz pokaz z nową konfiguracją.',
            previewTitle: 'Podgląd ustawień',
            albumsPreviewLabel: 'Albumy',
            tempoPreviewLabel: 'Tempo',
            noAlbumsSelected: 'Nie wybrano albumów',
            selectedSuffix: 'wybrane',
            mediaInSourcesSuffix: 'mediów łącznie w źródłach',
            chooseAlbums: 'Wybierz albumy do pokazu',
            secondsPerPhoto: 's na zdjęcie',
            invalidValue: 'Brak poprawnej wartości',
            refreshEveryPrefix: 'Odświeżanie nowych zdjęć co',
            refreshEverySuffix: 's',
            fillNumbers: 'Uzupełnij oba pola liczbowe',
            explanation: 'Pokaz będzie cyklicznie sprawdzał, czy w wybranych albumach pojawiły się nowe zdjęcia, i dopnie je na koniec kolejki bez zatrzymywania odtwarzania.',
        },
        menu: {
            title: 'Menu',
            saved: 'Menu zapisane. Zmiany są już widoczne na stronie dla gości.',
            saveFailed: 'Nie udało się zapisać menu.',
            helpText: 'Każdy blok menu może mieć własne rodzaje posiłku, np. główne menu, słodki stół albo napoje.',
            moveBlockUp: 'Przesuń blok wyżej',
            moveBlockDown: 'Przesuń blok niżej',
            moveSectionUp: 'Przesuń rodzaj wyżej',
            moveSectionDown: 'Przesuń rodzaj niżej',
            mealType: 'Rodzaj posiłku',
            moveItemUp: 'Przesuń danie wyżej',
            moveItemDown: 'Przesuń danie niżej',
            itemPlaceholder: 'Np. Rosół królewski',
            itemDescriptionPlaceholder: 'Opcjonalny opis z karty menu lub sali.',
            summaryBlocks: 'bloków',
            summarySections: 'rodzajów',
            summaryItems: 'dań',
            dirty: 'Robocze zmiany',
            clean: 'Zapisane',
            addBlock: 'Dodaj blok menu',
            save: 'Zapisz menu',
            savedTitle: 'Zapisano',
            newBlock: 'Nowy blok menu',
            deleteBlock: 'Usuń blok',
            blockName: 'Nazwa bloku menu',
            deleteSection: 'Usuń rodzaj',
            itemLabel: 'Danie',
            itemName: 'Nazwa dania',
            itemDescription: 'Opis',
            addItem: 'Dodaj danie',
            addSection: 'Dodaj rodzaj posiłku',
            emptyBlocksTitle: 'Brak bloków menu',
            emptyBlocksDescription: 'Zacznij od dodania pierwszego bloku, np. głównego menu, słodkiego stołu albo napojów.',
            addFirstBlock: 'Dodaj pierwszy blok',
        },
        guests: {
            title: 'Lista gości',
            helpText: 'Zarządzaj zaproszonymi, potwierdzeniami obecności i noclegami.',
            empty: 'Lista gości jest jeszcze pusta.',
            searchPlaceholder: 'Nazwisko, hotel, pokój',
            shownPrefix: 'Pokazano',
            shownMiddle: 'z',
            shownSuffix: 'osób',
            addGuestsAriaLabel: 'Dodawanie gości',
            addGroup: 'Dodaj grupę',
            addPerson: 'Dodaj osobę',
            attendance: 'Obecność',
            noFilterResults: 'Brak osób pasujących do wybranych filtrów.',
            peopleSuffix: 'osób',
            byGuestTypes: 'według typów gości',
            transportToSet: 'Szczegóły do ustalenia',
            none: 'Brak',
            editPerson: 'Edytuj osobę',
            deletePerson: 'Usuń osobę',
            deleteConfirm: 'Czy na pewno chcesz usunąć tę osobę z listy gości?',
            forms: {
                addGroupTitle: 'Dodaj grupę',
                addGroupDescription: 'Utwórz jedną grupę zaproszenia, np. Anna i Jan Kowalscy wraz z dziećmi.',
                addPersonTitle: 'Dodaj gościa',
                addPersonDescription: 'Po dodaniu możesz od razu wpisać kolejną osobę z tymi samymi ustawieniami.',
                addAndNext: 'Dodaj i następny',
                addAndClose: 'Dodaj i zamknij',
                category: 'Kategoria',
                needsAccommodation: 'Potrzebuje noclegu',
                invitationGroup: 'Grupa zaproszenia',
                noGroup: 'Bez grupy',
                relationshipInGroup: 'Relacja w grupie',
                partner: 'Partner/partnerka',
                child: 'Dziecko',
                otherPerson: 'Inna osoba',
                hotel: 'Hotel',
                needsTransport: 'Potrzebuje transportu',
                transport: 'Transport',
                note: 'Notatka',
                addNote: 'Dodaj notatkę',
                groupName: 'Nazwa grupy',
                personOne: 'Osoba 1',
                personTwo: 'Osoba 2',
                childrenTitle: 'Dzieci w zaproszeniu',
                addChild: 'Dodaj dziecko',
                noChildren: 'Brak dzieci w tej grupie.',
                age: 'Wiek',
                accommodationData: 'Dane noclegu',
                transportData: 'Dane transportu',
                transportNote: 'Notatka o transporcie',
                room: 'Pokój',
                saveAccommodation: 'Zapisz nocleg',
                saveTransport: 'Zapisz transport',
                name: 'Imię i nazwisko',
                primaryPerson: 'Główna osoba',
                noValue: 'Brak',
                namePlaceholder: 'Np. Anna Kowalska',
                partnerNamePlaceholder: 'Np. Jan Kowalski',
                childNamePlaceholder: 'Np. Zosia Kowalska',
                hotelPlaceholder: 'Np. Willa Poprad',
                roomPlaceholder: 'Np. 12 / apartament rodzinny',
                accommodationRoomPlaceholder: 'Np. 12 / rodzinny / do ustalenia',
                notePlaceholder: 'Dieta, transport, dodatkowe ustalenia',
                transportModalPlaceholder: 'Np. bus z hotelu, transport po poprawinach, fotelik dla dziecka',
                familyNamePlaceholder: 'Np. Anna i Jan Kowalscy wraz z dziećmi',
                transportNotesPlaceholder: 'Np. bus z hotelu, powrót po weselu',
                child3To10: '3-10 lat',
                childUnder3: 'Do 3 lat',
                childOver10: 'Powyżej 10 lat',
                defaultAttendance: 'Domyślna obecność',
            },
            attendanceOptions: {
                pending: 'Oczekuje',
                confirmed: 'Potwierdzono',
                declined: 'Nieobecny',
                unconfirmed: 'Niepotwierdzone',
            },
            table: {
                person: 'Osoba',
                category: 'Kategoria',
                attendance: 'Obecność',
                accommodation: 'Nocleg',
                transport: 'Transport',
                note: 'Notatka',
                actions: 'Akcje',
                yes: 'Tak',
                no: 'Nie',
                hotelToSet: 'Hotel do ustalenia',
            },
            ageGroups: {
                adult: 'Dorosły',
                childUnder3: 'Dziecko do 3 lat',
                child3To10: 'Dziecko 3-10 lat',
                childOver10: 'Dziecko powyżej 10 lat',
                vendor: 'Usługodawca',
            },
            summary: {
                confirmed: 'Potwierdziło',
                totalWithCouple: 'Razem z Parą',
                adults: 'Dorośli',
                vendors: 'Usługodawcy',
                vendorsLong: 'Usługodawcy',
                adultsAndChildrenOver10: 'Dorośli + dzieci 10+',
            },
            errors: {
                addPerson: 'Nie udało się dodać osoby do listy gości.',
                addFamily: 'Nie udało się dodać rodziny do listy gości.',
                savePerson: 'Nie udało się zapisać osoby.',
                attendance: 'Nie udało się zmienić statusu obecności.',
                accommodationToggle: 'Nie udało się zmienić noclegu.',
                accommodationSave: 'Nie udało się zapisać danych noclegu.',
                transportToggle: 'Nie udało się zmienić transportu.',
                transportSave: 'Nie udało się zapisać danych transportu.',
                deletePerson: 'Nie udało się usunąć osoby z listy gości.',
            },
        },
    },
} as const;
